### PR TITLE
Elixir only

### PR DESCRIPTION
**Pull request by InoMurko**
All kudos to @masonforest! 
We needed to fix dialyzer as well. Expanding his work.

### CODE REVIEW

**Comment by masonforest** [comment]
Thanks for picking this up @InoMurko ! I'm good with this getting merged and I'll close my PR. Looks like @ayrat555 already approved mine. Objections @hayesgm / @atoulme /  anyone?

**Comment by atoulme** [comment]
None here.

**Comment by unnawut** [comment]
Hi all! Can we get this PR merged?

We're churning out some new packages for our network and requires this change a new `:libsecp256k1` release. Thanks!

**Comment by hayesgm** [comment]
Hey, I'm having trouble getting this to run, want to help so I can update the README?

So far I've done:

```
brew install automake
brew install libtool
mix compile
```

but I'm getting the following error:

```
configure: Using jni: no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'
```

**Comment by InoMurko** [comment]
Seems like this is coming directly from libsecp256k1_source https://github.com/bitcoin-core/secp256k1
```
./deps/libsecp256k1_source/config.status
```
Maybe running 
```
$ ./autogen.sh
$ ./configure
```
inside `deps/libsecp256k1_source` would spit out what dependencies you might be missing?

**Comment by hayesgm** [comment]
@InoMurko After running those commands (they succeeded), I was able to compile, however, it doesn't not appear to load correctly:

```bash
iex -S mix
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]

make: `priv/libsecp256k1_nif.so' is up to date.
Interactive Elixir (1.10.0) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> priv_key = :crypto.strong_rand_bytes(32)
<<50, 141, 215, 172, 229, 239, 186, 203, 45, 144, 122, 21, 36, 41, 184, 98, 116,
  192, 168, 225, 192, 163, 130, 39, 125, 46, 165, 185, 150, 133, 197, 168>>
iex(2)> :libsecp256k1.ec_pubkey_create(priv_key, :compressed)
=ERROR REPORT==== 30-Jan-2020::14:03:16.445678 ===
Error in process <0.185.0> with exit value:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,"lib/secp256k1.ex"},{line,9}]},
  {code_server,'-handle_on_load/5-fun-0-',1,
               [{file,"code_server.erl"},{line,1340}]}]}

=WARNING REPORT==== 30-Jan-2020::14:03:16.446588 ===
The on_load function for module libsecp256k1 returned:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,...},{...}]},
  {code_server,'-handle_on_load/5-fun-0-',1,[{...}|...]}]}

=ERROR REPORT==== 30-Jan-2020::14:03:16.450573 ===
Error in process <0.187.0> with exit value:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,"lib/secp256k1.ex"},{line,9}]},
  {code_server,'-handle_on_load/5-fun-0-',1,
               [{file,"code_server.erl"},{line,1340}]}]}

=WARNING REPORT==== 30-Jan-2020::14:03:16.451284 ===
The on_load function for module libsecp256k1 returned:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /home/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,...},{...}]},
  {code_server,'-handle_on_load/5-fun-0-',1,[{...}|...]}]}

** (UndefinedFunctionError) function :libsecp256k1.ec_pubkey_create/2 is undefined (module :libsecp256k1 is not available)
    (libsecp256k1 0.2.0) :libsecp256k1.ec_pubkey_create(<<50, 141, 215, 172, 229, 239, 186, 203, 45, 144, 122, 21, 36, 41, 184, 98, 116, 192, 168, 225, 192, 163, 130, 39, 125, 46, 165, 185, 150, 133, 197, 168>>, :compressed)
```

**Comment by masonforest** [comment]
Hmmmm. This was working fine last time I used it. Maybe upstream changes broke it? I should have double checked it was still working before before merging 😬 

I'm getting the same error as @hayesgm now:

```
=ERROR REPORT==== 30-Jan-2020::17:25:40.894097 ===
Error in process <0.185.0> with exit value:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): image not found'"}}},
 [{libsecp256k1,init,0,[{file,"lib/secp256k1.ex"},{line,9}]},
  {code_server,'-handle_on_load/5-fun-0-',1,
               [{file,"code_server.erl"},{line,1340}]}]}

=WARNING REPORT==== 30-Jan-2020::17:25:40.895119 ===
The on_load function for module libsecp256k1 returned:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): image not found'"}}},
 [{libsecp256k1,init,0,[{file,...},{...}]},
  {code_server,'-handle_on_load/5-fun-0-',1,[{...}|...]}]}

=ERROR REPORT==== 30-Jan-2020::17:25:40.899267 ===
Error in process <0.187.0> with exit value:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): image not found'"}}},
 [{libsecp256k1,init,0,[{file,"lib/secp256k1.ex"},{line,9}]},
  {code_server,'-handle_on_load/5-fun-0-',1,
               [{file,"code_server.erl"},{line,1340}]}]}

=WARNING REPORT==== 30-Jan-2020::17:25:40.900138 ===
The on_load function for module libsecp256k1 returned:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): image not found'"}}},
 [{libsecp256k1,init,0,[{file,...},{...}]},
  {code_server,'-handle_on_load/5-fun-0-',1,[{...}|...]}]}

** (UndefinedFunctionError) function :libsecp256k1.ec_pubkey_create/2 is undefined (module :libsecp256k1 is not available)
    (libsecp256k1 0.1.10) :libsecp256k1.ec_pubkey_create(<<196, 250, 78, 181, 56, 55, 104, 163, 151, 135, 147, 57, 48, 27, 249, 155, 93, 238, 30, 160, 121, 117, 56, 81, 207, 137, 113, 232, 32, 166, 110, 143>>, :compressed)
```


I can look more into this later tonight!

Any hints @InoMurko ?

**Comment by InoMurko** [comment]
It works here:
```
iex(1)> priv_key = :crypto.strong_rand_bytes(32)
<<45, 123, 78, 1, 33, 184, 90, 112, 60, 89, 55, 145, 214, 238, 63, 70, 163, 144,
  15, 234, 185, 158, 179, 78, 47, 107, 157, 27, 151, 13, 161, 160>>
iex(2)> :libsecp256k1.ec_pubkey_create(priv_key, :compressed)
{:ok,
 <<3, 246, 37, 79, 198, 184, 175, 159, 71, 84, 52, 173, 76, 44, 207, 14, 119,
   110, 143, 168, 250, 30, 173, 133, 98, 203, 177, 59, 21, 49, 155, 191, 42>>}
```
We've been pointing at this branch for a very long time: https://github.com/omisego/elixir-omg/blob/master/apps/omg_watcher/mix.exs#L40
I've also checked our CI/CD and we're not setting any custom compiler flags of sorts.

Does this work?
```
hash = <<218, 245, 167, 121, 174, 151, 47, 151, 33, 151, 48, 61, 123, 87, 71, 70, 199,
  239, 131, 234, 218, 192, 242, 121, 26, 210, 61, 185, 46, 76, 142, 83>>
private_key = Base.decode16!("4646464646464646464646464646464646464646464646464646464646464646", case: :lower)
:libsecp256k1.ecdsa_sign_compact(hash, private_key, :default, <<>>)
:libsecp256k1.ec_pubkey_create(private_key, :uncompressed)
```

All I could really find find at the moment is https://stackoverflow.com/a/45204797

**Comment by masonforest** [comment]
I did a `brew install gmp` and `mix compile` within the root project directory and now I'm getting this error:
```
iex -S mix
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

make: `priv/libsecp256k1_nif.so' is up to date.
Interactive Elixir (1.10.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> priv_key = :crypto.strong_rand_bytes(32)
<<213, 58, 142, 122, 225, 202, 199, 138, 191, 157, 30, 106, 180, 239, 234, 81,
  32, 179, 16, 179, 66, 118, 133, 203, 226, 135, 156, 113, 16, 43, 195, 33>>
iex(2)> :libsecp256k1.ec_pubkey_create(priv_key, :compressed)
=ERROR REPORT==== 30-Jan-2020::17:43:02.112437 ===
Error in process <0.185.0> with exit value:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,"lib/secp256k1.ex"},{line,9}]},
  {code_server,'-handle_on_load/5-fun-0-',1,
               [{file,"code_server.erl"},{line,1340}]}]}

=WARNING REPORT==== 30-Jan-2020::17:43:02.113251 ===
The on_load function for module libsecp256k1 returned:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,...},{...}]},
  {code_server,'-handle_on_load/5-fun-0-',1,[{...}|...]}]}

=ERROR REPORT==== 30-Jan-2020::17:43:02.117242 ===
Error in process <0.187.0> with exit value:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,"lib/secp256k1.ex"},{line,9}]},
  {code_server,'-handle_on_load/5-fun-0-',1,
               [{file,"code_server.erl"},{line,1340}]}]}

=WARNING REPORT==== 30-Jan-2020::17:43:02.117950 ===
The on_load function for module libsecp256k1 returned:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,...},{...}]},
  {code_server,'-handle_on_load/5-fun-0-',1,[{...}|...]}]}

** (UndefinedFunctionError) function :libsecp256k1.ec_pubkey_create/2 is undefined (module :libsecp256k1 is not available)
    (libsecp256k1 0.1.10) :libsecp256k1.ec_pubkey_create(<<213, 58, 142, 122, 225, 202, 199, 138, 191, 157, 30, 106, 180, 239, 234, 81, 32, 179, 16, 179, 66, 118, 133, 203, 226, 135, 156, 113, 16, 43, 195, 33>>, :compressed)
iex(2)>
```
 

I also [reverted the merge](https://github.com/exthereum/libsecp256k1/pull/21) while we figure this out...

**Comment by masonforest** [comment]
@InoMurko nah, same error unfortunately 😕 

```
iex(2)> hash = <<218, 245, 167, 121, 174, 151, 47, 151, 33, 151, 48, 61, 123, 87, 71, 70, 199,
...(2)>   239, 131, 234, 218, 192, 242, 121, 26, 210, 61, 185, 46, 76, 142, 83>>
<<218, 245, 167, 121, 174, 151, 47, 151, 33, 151, 48, 61, 123, 87, 71, 70, 199,
  239, 131, 234, 218, 192, 242, 121, 26, 210, 61, 185, 46, 76, 142, 83>>
iex(3)> private_key = private_key = Base.decode16!("4646464646464646464646464646464646464646464646464646464646464646", case: :lower)
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
iex(4)> :libsecp256k1.ecdsa_sign_compact(hash, private_key, :default, <<>>)
=ERROR REPORT==== 30-Jan-2020::17:45:24.757071 ===
Error in process <0.194.0> with exit value:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,"lib/secp256k1.ex"},{line,9}]},
  {code_server,'-handle_on_load/5-fun-0-',1,
               [{file,"code_server.erl"},{line,1340}]}]}

=WARNING REPORT==== 30-Jan-2020::17:45:24.757935 ===
The on_load function for module libsecp256k1 returned:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,...},{...}]},
  {code_server,'-handle_on_load/5-fun-0-',1,[{...}|...]}]}

=ERROR REPORT==== 30-Jan-2020::17:45:24.759894 ===
Error in process <0.196.0> with exit value:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,"lib/secp256k1.ex"},{line,9}]},
  {code_server,'-handle_on_load/5-fun-0-',1,
               [{file,"code_server.erl"},{line,1340}]}]}

** (UndefinedFunctionError) function :libsecp256k1.ecdsa_sign_compact/4 is undefined (module :libsecp256k1 is not available)
    (libsecp256k1 0.1.10) :libsecp256k1.ecdsa_sign_compact(<<218, 245, 167, 121, 174, 151, 47, 151, 33, 151, 48, 61, 123, 87, 71, 70, 199, 239, 131, 234, 218, 192, 242, 121, 26, 210, 61, 185, 46, 76, 142, 83>>, "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", :default, "")
=WARNING REPORT==== 30-Jan-2020::17:45:24.760761 ===
The on_load function for module libsecp256k1 returned:
{{badmatch,{error,{load_failed,"Failed to load NIF library: 'dlopen(/Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so, 2): Symbol not found: _secp256k1_ecdsa_recover\n  Referenced from: /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so\n  Expected in: flat namespace\n in /Users/masonf/src/libsecp256k1/_build/dev/lib/libsecp256k1/priv/libsecp256k1_nif.so'"}}},
 [{libsecp256k1,init,0,[{file,...},{...}]},
  {code_server,'-handle_on_load/5-fun-0-',1,[{...}|...]}]}
```

**Comment by InoMurko** [comment]
can you guys pls share your compilation logs? 
https://gist.github.com/InoMurko/1344105edf881debb148cfc3395aef53

NIF not loading basically means it wasn't compiled properly...

**Comment by masonforest** [comment]
Compilation logs: https://gist.github.com/masonforest/7c495968ed37cf699adc37db0af08ef0

Elixir Version: 1.10.0
OTP Version:  22

🤔

**Comment by InoMurko** [comment]
Will go over this log tomorrow @masonforest ! Thanks! Fyi, I'm on elixir 1.8.1, Erlang/OTP 21

**Comment by unnawut** [comment]
Not sure if this is the solution but I got away from "Failed to load NIF library" and "symbol not found" most of the time by clearing the deps source and the builds together:

```
$ mix do clean, deps.clean --all, deps.get, compile
```

The reason for having to `mix deps.clean --all` is because some compile steps put the build assets right into the source folders and those don't get cleaned up by `mix clean` nor `mix deps.clean --build`, so it's compiling with stale data/assets. `--all` is needed because this also applies to other compile-from-source libraries as well.

**Pull request merged**
